//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_MOVIMIENTO
    {
        public int id { get; set; }
        public int fk_id_movimiento { get; set; }
        public Nullable<int> fk_id_apertura { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> monto { get; set; }
        public string motivo { get; set; }
    
        public virtual APERTURA APERTURA { get; set; }
        public virtual MOVIMIENTO MOVIMIENTO { get; set; }
    }
}
