//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCION
    {
        public int id { get; set; }
        public Nullable<int> condicion { get; set; }
        public Nullable<int> descuento { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
    }
}
